<a href="https://colab.research.google.com/github/Varshinie13/Python-Learning-CaseStudies/blob/main/Python_DA_Assignment_1%E2%80%94Numpy_and_Pandas_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy Array Operations:  

In [1]:
import numpy as np

In [2]:
#Create a 1D NumPy Array:

temperatures_w1 = np.array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1


array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [5]:
#Inspection and Properties:

#Inspect the shape
print(f"The shape of the array : ",temperatures_w1.shape)

#Inspect the DataType
print(f"The array data Type is: ",temperatures_w1.dtype)

#inspect Number of elements in array
print(f"The number of elements in array: ",temperatures_w1.size)

The shape of the array :  (7,)
The array data Type is:  float64
The number of elements in array:  7


In [7]:
#Array Operations:

#Convert the temperatures_w1 from Celsius to Fahrenheit :
Fahrenheit = (temperatures_w1 * 9/5) + 32
print(f"The celsius Temperatures: ",temperatures_w1)
print(f"The Fahrenheit Temperatures: ",Fahrenheit)

The celsius Temperatures:  [22.5 25.3 20.8 23.4 26.1 24.8 21.9]
The Fahrenheit Temperatures:  [72.5  77.54 69.44 74.12 78.98 76.64 71.42]


In [13]:
# maximum temperature of the week
max_temp = np.max(temperatures_w1)
print(f"The Maximum Temparature of the week is : ",max_temp)
#minimum temperature of the week
min_temp = np.min(temperatures_w1)
print(f"The Minimum Temparature of the week is : ",min_temp)

The Maximum Temparature of the week is :  26.1
The Minimum Temparature of the week is :  20.8


In [15]:
#mean temparature of the week
Avg_temp = np.mean(temperatures_w1)
print(f"The Average Temparature of the week is : {Avg_temp:.2f}")

The Average Temparature of the week is : 23.54


Array Slicing and Indexing:  

In [20]:
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [28]:
# Extract the temperatures for the first three days of the week.
print(f"The temperatures for the first three days of the weeks is: ",temperatures_w1[:3])
# Extract the temperatures for the weekend (last two days).
print(f"The temperatures for weekend is: ",temperatures_w1[-2:])
# Extract the temperatures for the middle three days of the week.
print(f"The temperatures for the middle three days of the weeks is: ",temperatures_w1[2:5])




The temperatures for the first three days of the weeks is:  [22.5 25.3 20.8]
The temperatures for weekend is:  [24.8 21.9]
The temperatures for the middle three days of the weeks is:  [20.8 23.4 26.1]


Create a 2D Array:  

In [31]:
#Create a 2D NumPy array named temperatures

temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9] ,
[19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]] )
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [32]:
#Inspect and Slice the 2D Array:


#Inspect the shape
print(f"The shape of the 2d - array : ",temperatures.shape)

#Inspect the DataType
print(f"The 2d- array data Type is: ",temperatures.dtype)

#inspect Number of elements in array
print(f"The number of elements in 2d - array: ",temperatures.size)

The shape of the 2d - array :  (2, 7)
The 2d- array data Type is:  float64
The number of elements in 2d - array:  14


In [33]:
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [36]:
#Extract the temperatures for each week and the weekends (last two days) for both weeks.

print(f"The Week day Temparatures: ",temperatures[:5,:5])
print(f"The Week end Temparatures: ",temperatures[-2:,-2:])

The Week day Temparatures:  [[22.5 25.3 20.8 23.4 26.1]
 [19.2 22.5 21.3 24.  23.5]]
The Week end Temparatures:  [[24.8 21.9]
 [22.8 20.1]]


Pandas Series:  

In [37]:
import pandas as pd

In [39]:
#Creating Pandas Series:
marks = [95, 92, 89, 85, 80 ]
indices = ["Rank1","Rank2","Rank3","Rank4","Rank5"]

scores = pd.Series(marks, index = indices)
scores

,0
Rank1,95
Rank2,92
Rank3,89
Rank4,85
Rank5,80


Indexing and Slicing:  

In [54]:
# Use the integer index position to access the mark of the 1st rank student.

print(f"The 1st Rank student Marks is : ",scores.Rank1 )
print("------------------------------------------------------------------------")
# Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.

print(f"The Top 3 ranks:\n",scores.loc['Rank1':'Rank3'])
print("------------------------------------------------------------------------")

# Use the iloc accessor to retrieve the mark of the 3rd-ranked student.

print(f"The 3rd ranked student :",scores.iloc[2])
print("------------------------------------------------------------------------")
# Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.

print(f"Marks greater than 90:\n",scores[(scores>90)])

The 1st Rank student Marks is :  95
------------------------------------------------------------------------
The Top 3 ranks:
 Rank1    95
Rank2    92
Rank3    89
dtype: int64
------------------------------------------------------------------------
The 3rd ranked student : 89
------------------------------------------------------------------------
Marks greater than 90:
 Rank1    95
Rank2    92
dtype: int64


Manipulating Series:

In [56]:
scores

,0
Rank1,95
Rank2,92
Rank3,89
Rank4,85
Rank5,80


In [65]:
# Modify the mark of the student with the 1st rank to 100.
# Remove the entry corresponding to the last rank from the Series.
scores.iloc[0]=100
scores
scores.drop('Rank5',inplace = True)




,0
Rank1,100
Rank2,92
Rank3,89
Rank4,85


In [68]:
# Compute the CGPA by dividing each mark in the Series by 10.
cgpa = scores/10
print(f"CGPA:\n",cgpa)

CGPA:
 Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: object


Pandas DataFrame:  

In [72]:
#Creating Pandas DataFrame:

Transactions = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110 ],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing','Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South','North' ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400 ]}
df = pd.DataFrame(Transactions)
df

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


Data Exploration:  

In [73]:
#Display the transactions DataFrame  - head

df.head()

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200


In [75]:
#Display the transactions DataFrame  - tail
df.tail()

,TransactionID,ProductCategory,Region,Amount
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [77]:
#Display the transactions DataFrame  - shape
df.shape

(10, 4)

In [78]:
#Display the transactions DataFrame  - Column names
df.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [79]:
#Display the transactions DataFrame  - datatypes
df.dtypes

,0
TransactionID,int64
ProductCategory,object
Region,object
Amount,int64


In [80]:
#Display only the 'ProductCategory' and 'Amount' columns.

df[['ProductCategory','Amount']]

,ProductCategory,Amount
0,Electronics,200
1,Clothing,150
2,Electronics,300
3,Furniture,450
4,Clothing,200
5,Electronics,250
6,Furniture,300
7,Clothing,180
8,Furniture,350
9,Electronics,400


In [83]:
df

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [84]:
# Retrieve the last 3 columns of the DataFrame using iloc or loc.

df.iloc[0:,-3:]

,ProductCategory,Region,Amount
0,Electronics,North,200
1,Clothing,South,150
2,Electronics,North,300
3,Furniture,East,450
4,Clothing,West,200
5,Electronics,North,250
6,Furniture,East,300
7,Clothing,West,180
8,Furniture,South,350
9,Electronics,North,400


In [87]:
# Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

df[(df['Region'] == 'North') & (df['Amount'] >= 200)]

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
2,103,Electronics,North,300
5,106,Electronics,North,250
9,110,Electronics,North,400


In [88]:
# Find the value counts for the 'ProductCategory' column.

df.value_counts('ProductCategory')

,count
ProductCategory,
Electronics,4
Clothing,3
Furniture,3


In [91]:
#Find the unique values in the 'Region' column.

df['Region'].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [93]:
# Group by 'Region' and find the mean amount for each region.

df.groupby('Region')['Amount'].mean()

,Amount
Region,
East,375.0
North,287.5
South,250.0
West,190.0


Manipulating the DataFrame:  

In [100]:
Transactions = {
    'TransactionID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110 ],
    'ProductCategory': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing','Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    'Region': ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South','North' ],
    'Amount': [200, 150, 300, 450, 200, 250, 300, 180, 350, 400 ]}
Tansactions = pd.DataFrame(Transactions)
Tansactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,150
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [101]:
# Modify the 'Amount' for the transaction with TransactionID 102 to 165.

Tansactions.loc[Tansactions['TransactionID'] == 102,'Amount'] = 165

In [102]:
Tansactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,165
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
8,109,Furniture,South,350
9,110,Electronics,North,400


In [103]:
#Add a new column 'Discount' by calculating 10% of the 'Amount'.

Tansactions['Discount'] = Tansactions['Amount']*0.10
Tansactions

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
8,109,Furniture,South,350,35.0
9,110,Electronics,North,400,40.0


In [106]:
#Remove the row with TransactionID 109.
Tansactions = Tansactions[Tansactions['TransactionID']!= 109]
Tansactions

,TransactionID,ProductCategory,Region,Amount,Discount
0,101,Electronics,North,200,20.0
1,102,Clothing,South,165,16.5
2,103,Electronics,North,300,30.0
3,104,Furniture,East,450,45.0
4,105,Clothing,West,200,20.0
5,106,Electronics,North,250,25.0
6,107,Furniture,East,300,30.0
7,108,Clothing,West,180,18.0
9,110,Electronics,North,400,40.0


In [107]:
#Delete the 'Discount' column from the DataFrame.
Tansactions = Tansactions.drop('Discount',axis = 1)
Tansactions

,TransactionID,ProductCategory,Region,Amount
0,101,Electronics,North,200
1,102,Clothing,South,165
2,103,Electronics,North,300
3,104,Furniture,East,450
4,105,Clothing,West,200
5,106,Electronics,North,250
6,107,Furniture,East,300
7,108,Clothing,West,180
9,110,Electronics,North,400
